/**
 * Exports the legal pages the website has to host, from the sources of truth
 * in this repo, into web/legal/.
 *
 * Why this is a script and not a copy and paste job:
 *
 * The EULA is not a document in this repository. It is rows in
 * eula_versions, inserted by migrations, and the app renders whichever row
 * sorts newest. The website's /open-mics/terms page has to show the same
 * text, because the app links to that URL as its terms of use and because
 * the agreement people accept in the app is the one the store reviewer
 * reads on the web. Hand-copying it works exactly once: the next EULA
 * version bump leaves the website showing an agreement nobody agreed to,
 * and nothing fails loudly when that happens.
 *
 * So the terms page is generated from the migration that publishes the
 * newest version, and regenerating is a command rather than an act of
 * discipline.
 *
 * The privacy policy has the same shape of problem in a milder form: the
 * in-app copy lives in src/features/legal/privacy-policy.ts and the
 * hostable copy in docs/privacy/PRIVACY_POLICY.md. Those two are kept in
 * step by hand today, which is a known and accepted seam. This script only
 * strips the internal preamble off the hostable copy so what lands in
 * web/legal/ is publishable as-is.
 *
 * Usage:  node scripts/export-legal.mjs
 * Output: web/legal/terms.md, web/legal/privacy.md
 *
 * Run it after any migration that publishes a new EULA version, and commit
 * the result. CI does not run it: the website repo is the consumer, and a
 * generated file that changes without a migration behind it would be a
 * confusing diff.
 */

import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const migrationsDir = join(root, 'supabase', 'migrations');
const outDir = join(root, 'web', 'legal');

/** Compares dotted numeric versions, newest last. */
function compareVersions(a, b) {
  const pa = a.split('.').map(Number);
  const pb = b.split('.').map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i += 1) {
    const diff = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (diff !== 0) {
      return diff;
    }
  }
  return 0;
}

/**
 * Every EULA body published by a migration, keyed by version. The dollar
 * quoting is what the migrations use, and it is what makes the bodies
 * extractable without a SQL parser: markdown inside single quotes would
 * have needed escaping and nobody would have written it that way.
 */
function collectEulaVersions() {
  const pattern =
    /insert\s+into\s+eula_versions\s*\([^)]*\)\s*values\s*\(\s*'([\d.]+)'\s*,\s*\$eula\$([\s\S]*?)\$eula\$\s*\)/gi;
  const found = new Map();
  for (const file of readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.sql'))
    .sort()) {
    const sql = readFileSync(join(migrationsDir, file), 'utf8');
    for (const match of sql.matchAll(pattern)) {
      const [, version, body] = match;
      found.set(version, { body: body.trim(), file });
    }
  }
  return found;
}

const versions = collectEulaVersions();
if (versions.size === 0) {
  console.error(
    'No EULA versions found in supabase/migrations. Either the insert shape changed\n' +
      'or this script is looking in the wrong place. Refusing to write an empty terms page.',
  );
  process.exit(1);
}

const newest = [...versions.keys()].sort(compareVersions).at(-1);
const { body, file } = versions.get(newest);

const privacySource = readFileSync(join(root, 'docs', 'privacy', 'PRIVACY_POLICY.md'), 'utf8');
// Everything above the first horizontal rule is a note to ourselves about
// how to host it, not part of the policy.
const separator = privacySource.indexOf('\n---\n');
if (separator === -1) {
  console.error(
    'docs/privacy/PRIVACY_POLICY.md has no --- separating the internal preamble\n' +
      'from the policy itself. Refusing to publish the preamble to the web.',
  );
  process.exit(1);
}
const privacy = privacySource.slice(separator + 5).trim();

const banner = (source, risk) =>
  `<!--\n` +
  `  Generated by scripts/export-legal.mjs in the Open-Mic-Discovery repo.\n` +
  `  Source of truth: ${source}\n` +
  `  Do not edit this file directly. Edit the source and regenerate, or\n` +
  `  ${risk}\n` +
  `-->\n\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, 'terms.md'),
  banner(
    `supabase/migrations/${file} (eula_versions ${newest})`,
    'the website will show an agreement nobody accepted in the app.',
  ) +
    body +
    '\n',
);
writeFileSync(
  join(outDir, 'privacy.md'),
  banner(
    'docs/privacy/PRIVACY_POLICY.md',
    'the hosted policy and the in-app policy will describe different apps.',
  ) +
    privacy +
    '\n',
);

console.log(`web/legal/terms.md    <- EULA ${newest} from ${file}`);
console.log(`web/legal/privacy.md  <- docs/privacy/PRIVACY_POLICY.md`);
console.log(
  `\nKnown EULA versions: ${[...versions.keys()].sort(compareVersions).join(', ')}. ` +
    `Published: ${newest}.`,
);
